### ISSUE TITLE
IDEA: Фича

### ISSUE THREAD

**Issue by MaximTheHuman** [MeteorsDetected/Old-World-Blues#65]
Здраствуйте. Я, Аллах. Хотел бы чтобы вы сделали игру, 2Д-экшон суть такова... Пользователь может играть космонавтами, охраной станции и злодеем. И если пользователь играет космонавтом то космонавты в космосе, каюты уютные набигают ассистенты и злодеи. Можно грабить оружейки...

**Comment by Voldirs** [comment]
Хуле тут так мало написано? На мемы сел должен был весь текст отдать
